### PR TITLE
Allow minimist to be upgraded -- SNYK-JS-MINIMIST-2429795 & SNYK-JS-M…

### PR DESCRIPTION
**Pull request by ben-b-ow**
…INIMIST-559764

### CODE REVIEW

**Comment by ben-b-ow** [comment]
For issue #21

**Comment by iriscoopers** [comment]
+1 for this bump please, @DanPurdy :)

**Comment by gbowne-quickbase** [comment]
Please please, it's a SUPER SIMPLE PR to merge in and it will resolve some critical NPM dependency errors @DanPurdy

**Comment by seperez** [comment]
@DanPurdy could you help us with a version that includes this change, as @gbowne-quickbase says it is a super simple PR to merge and it would help us a lot to the whole community.

Thank you very much!

**Comment by ben-b-ow** [comment]
Hi @DanPurdy would you be able to have a quick look please? Thanks a lot!

**Pull request closed without merging**
